name: Build Alpine Node.js

on:
  workflow_dispatch:
    inputs:
      NodeVersion:
        required: true
        description: 'Node.js version to build (ex: v12.4.0)'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
         docker build --file Dockerfile --tag alpine_nodejs:${{github.event.inputs.NodeVersion}} --build-arg NodeVersion=${{github.event.inputs.NodeVersion}} .
    - name: Copy alpine node.js out
      run: |
         mkdir $RUNNER_TEMP/alpine_node
         docker run --rm -v $RUNNER_TEMP/alpine_node:/node_output alpine_nodejs:${{github.event.inputs.NodeVersion}}
    - name: Upload alpine node.js
      uses: actions/upload-artifact@v2
      with:
        name: alpine_nodejs
        path:  ${{runner.temp}}/alpine_node
